# This workflow trigger on push to any branch.
name: Deploy alerts to GCP
on:
  push:
    paths:
      - 'nais/alerterator.yml'
      - 'nais/dev-gcp.json'
      - 'nais/prod-gcp.json'
      - '.github/workflows/apply-alerts.yml'
    branches:
      - 'master'
      - 'dev-**'

jobs:
  deploy-alerts-dev-gcp:
    name: Deploy Alerts to dev-gcp
    if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/master') # Deploy if branch is either master or dev-*
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/alerterator.yml
          VARS: nais/dev-gcp.json

  deploy-alerts-prod-gcp:
    name: Deploy Alerts to prod-gcp
    if: startsWith(github.ref, 'refs/heads/master')  # If the branch is master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/alerterator.yml
          VARS: nais/prod-gcp.json
